version: '3.0'
services:
  gocdserver:
    build: ./server
    image: "l0g1g06/gocdserver"
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - "./server/data:/godata"
  pythonagent:
    build: ./agent/pythonAgent
    image: "l0g1g06/pythonagent"
    ports:
      - "8001:8001"
    volumes:
      - "./agent/pythonAgent/data:/godata"
  golangagent:
    build: ./agent/goAgent
    image: "l0g1g06/golangagent"
    volumes:
      - "./agent/goAgent/data:/godata"